# Generated by Django 3.2.6 on 2021-09-10 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20210907_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
    ]
